package gunna.gui;

import java.io.IOException;
import java.util.Collections;

import gunna.MainWindow;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * Represents a dialog box consisting of an ImageView to represent the speaker's face
 * and a label containing text from the speaker.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;
    @FXML
    private ImageView displayPicture;

    private DialogBox(String text, Image img) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }

        dialog.setText(text);
        dialog.maxWidthProperty().bind(widthProperty().multiply(0.72));
        if (img == null) {
            displayPicture.setManaged(false);
            displayPicture.setVisible(false);
        } else {
            displayPicture.setImage(img);
        }
    }

    /**
     * Flips the dialog box such that the ImageView is on the left and text on the right.
     */
    private void flip() {
        ObservableList<Node> tmp = FXCollections.observableArrayList(this.getChildren());
        Collections.reverse(tmp);
        getChildren().setAll(tmp);
        setAlignment(Pos.TOP_LEFT);
    }

    /**
     * Creates a right-aligned dialog that displays a user's command without an avatar.
     *
     * @param text The command entered by the user.
     * @return A dialog styled as a user message.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text, null);
        dialogBox.getStyleClass().add("user-dialog");
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog that displays a normal Gunna response.
     *
     * @param text The response generated by Gunna.
     * @param img The image representing Gunna.
     * @return A dialog styled as a normal Gunna message.
     */
    public static DialogBox getGunnaDialog(String text, Image img) {
        DialogBox dialogBox = new DialogBox(text, img);
        dialogBox.flip();
        dialogBox.getStyleClass().add("gunna-dialog");
        return dialogBox;
    }

    /**
     * Creates a Gunna dialog for a command error.
     *
     * @param text The explanatory error message.
     * @param img The image representing Gunna.
     * @return A visibly distinct error dialog.
     */
    public static DialogBox getErrorDialog(String text, Image img) {
        DialogBox dialogBox = new DialogBox("Error\n" + text, img);
        dialogBox.flip();
        dialogBox.getStyleClass().add("error-dialog");
        return dialogBox;
    }
}
